DROP TABLE IF EXISTS bonus;

DROP TABLE IF EXISTS operator;

DROP TABLE IF EXISTS promotion;

DROP TABLE IF EXISTS promotionbalance;

DROP TABLE IF EXISTS quota;

DROP TABLE IF EXISTS tenant;

DROP TABLE IF EXISTS user;