DROP TABLE IF EXISTS BONUS;

DROP TABLE IF EXISTS OPERATOR;

DROP TABLE IF EXISTS PROMOTION;

DROP TABLE IF EXISTS PROMOTIONBALANCE;

DROP TABLE IF EXISTS QUOTA;

DROP TABLE IF EXISTS TENANT;

DROP TABLE IF EXISTS USER;