 CREATE TABLE bonus
  (
     id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
     userid         BIGINT,
     creationtime   BIGINT,
     updatetime     BIGINT,
     size           BIGINT,
     targetuserid   BIGINT,
     targetquotaid  BIGINT,
     activationtime BIGINT,
     promotionid    INTEGER,
     volumetype     SMALLINT,
     tenantid       INTEGER,
     PRIMARY KEY (id)
  );

CREATE TABLE operator
  (
     id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
     name         VARCHAR(32),
     creationtime BIGINT,
     updatetime   BIGINT,
     PASSWORD     VARCHAR(255),
     tenantid     INTEGER,
     status       SMALLINT,
     PRIMARY KEY (id)
  );

CREATE TABLE promotion
  (
     id                  INTEGER GENERATED BY DEFAULT AS IDENTITY,
     name                VARCHAR(64),
     creationtime        BIGINT,
     updatetime          BIGINT,
     description         VARCHAR(255),
     rule                VARCHAR(255),
     status              SMALLINT,
     lastupdateoperator  INTEGER,
     bonusexpirationtime BIGINT,
     tenantid            INTEGER,
     starttime           BIGINT,
     endtime             BIGINT,
     maximum             BIGINT,
     PRIMARY KEY (id)
  );

CREATE TABLE promotionbalance
  (
     id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
     creationtime BIGINT,
     updatetime   BIGINT,
     promotionid  INTEGER,
     balance      BIGINT,
     maximum      BIGINT,
     reserved     BIGINT,
     PRIMARY KEY (id)
  );

CREATE TABLE quota
  (
     id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
     creationtime   BIGINT,
     updatetime     BIGINT,
     userid         BIGINT,
     maximum        BIGINT,
     balance        BIGINT,
     activationtime BIGINT,
     expirationtime BIGINT,
     volumetype     SMALLINT,
     tenantid       INTEGER,
     username       VARCHAR(255),
     reserved       BIGINT,
     PRIMARY KEY (id)
  );

CREATE TABLE tenant
  (
     id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
     name         VARCHAR(64),
     creationtime BIGINT,
     updatetime   BIGINT,
     description  VARCHAR(255),
     cycletype    INTEGER,
     PRIMARY KEY (id)
  );  
  
CREATE TABLE user
  (
     id           BIGINT NOT NULL auto_increment,
     name         VARCHAR(32),
     creationtime BIGINT,
     updatetime   BIGINT,
     tenantid     INTEGER,
     PRIMARY KEY (id)
  );

create index bonus_user_idx on Bonus (userId);
create index promotion_tenant_idx on Promotion (tenantId);
create index balance_promotion_idx on PromotionBalance (promotionId);
create index quota_user_idx on Quota (userId);
create index quota_username_idx on Quota (userName);
create index user_name_idx on User (name);